version: "3.8"
services:
  cassandra:
    image: omvk97/cassandra # this image will initialize the database
    container_name: cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra1"
      CASSANDRA_CLUSTER_NAME: DevCluster
      CASSANDRA_DC: Denmark
    ports:
      - 9042:9042
    volumes:
      - "./cassandra/init.cql:/docker-entrypoint-initdb.d/init.cql"

  packageservice1:
    image: omvk97/packageservice
    container_name: packageservice1
    env_file:
      - .env
    ports:
      - 9001:80
  packageservice2:
    image: omvk97/packageservice
    container_name: packageservice2
    env_file:
      - .env
    ports:
      - 9002:80

  loadbalancer:
    image: nginx
    container_name: loadbalancer
    ports:
      - 8080:80
    depends_on:
      - packageservice1
      - packageservice2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
