version: "3"

services:
  
  packageservice:
    build:
      context: ./
      dockerfile: dockerfile.dev
    container_name: packageservice-dev
    environment:
      CASSANDRA_NODES: '["cassandra1", "cassandra2"]'
      CASSANDRA_LOCAL_DATACENTER: "Denmark"
    volumes:
      - ./src:/opt/app/src/ # for dev purposes
  
  cassandra1:
    image: cassandra
    container_name: cassandra1
    environment:
      CASSANDRA_SEEDS: cassandra1,cassandra2
      CASSANDRA_CLUSTER_NAME: DevCluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: Denmark
    ports:
      - 9042:9042
      - 7000:7000

  cassandra2:
    image: cassandra
    container_name: cassandra2
    environment:
      CASSANDRA_SEEDS: cassandra1,cassandra2
      CASSANDRA_CLUSTER_NAME: DevCluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: Denmark
    ports:
      - 9043:9042
      - 7001:7000