version: "3"

services:
  packageservice:
    build:
      context: ./
      dockerfile: dockerfile.dev
    container_name: packageservice-dev
    env_file:
      - .env.dev
    ports:
      - 9001:9001
    volumes:
      - ./src:/opt/app/src/ # for dev purposes

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: packageservice
      POSTGRES_PASSWORD: Packageservice_database_password1
      POSTGRES_DB: packageservice-database
    ports:
      - 5432:5432
    volumes:
      # Inside postgres we can specify sql script which is run in alphabetical order. This script creates the database
      - "./sql/blankdatabasestartup.sql:/docker-entrypoint-initdb.d/init.sql"
